
package view;

import core.Helper;
import dao.FaturaDao;
import dao.MusteriDao;
import dao.UrunDao;
import entity.Fatura;
import entity.Musteri;
import entity.Urun;
import entity.User;
import java.awt.Toolkit;
import java.util.List;
import java.sql.SQLException;
import java.awt.datatransfer.StringSelection;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public class MainFrame extends javax.swing.JFrame {
    private static User user;
    private DefaultTableModel musteriTableModel;
    private DefaultTableModel urunTableModel;
    private DefaultTableModel faturaTableModel;
    private ButtonGroup bg = new ButtonGroup();
    /**
     * Creates new form MainFrame
     */
    public MainFrame(User the_user) {
        initComponents();
        user = new User();
        user = the_user;
        String name = user.getName();
        jLabel1.setText("Hoşgeldin: " + name);
        
        //initComponents sonrası tablo modelleri
        musteriTableModel = new DefaultTableModel(new Object[]{"Müşteri ID","İsim","Mail"}, 0);
        tbl_musteri.setModel(musteriTableModel);
        
        urunTableModel = new DefaultTableModel(new Object[]{"ID", "Ürün Ad", "Fiyat"}, 0);
        tbl_urun.setModel(urunTableModel);
        
        faturaTableModel = new DefaultTableModel(new Object[]{"Fatura ID", "Müşteri ID", "Toplam Tutar"}, 0);
        tbl_fatura.setModel(faturaTableModel);
        
        //müşteri
        sil_musteri_item.setText("Seçili satırı sil.");
        copy_musteri_item.setText("Seçili satırı kopyala!");
        jPopupMenu1.add(copy_musteri_item);
        jPopupMenu1.add(sil_musteri_item);
        tbl_musteri.setComponentPopupMenu(jPopupMenu1);
        //ürün
        sil_urun_item.setText("Seçili satırı sil.");
        copy_urun_item.setText("Seçili satırı kopyala!");
        popUpUrun.add(copy_urun_item);
        popUpUrun.add(sil_urun_item);
        tbl_urun.setComponentPopupMenu(popUpUrun);
        //fatura
        sil_fatura_item.setText("Seçili satırı sil.");
        copy_fatura_item.setText("Seçili satırı kopyala!");
        popUpFatura.add(copy_fatura_item);
        popUpFatura.add(sil_fatura_item);
        tbl_fatura.setComponentPopupMenu(popUpFatura);
        
        bg.add(btn_urunTable_dosyaya_yaz);
        bg.add(btn_txt_area_dosyaya_yaz);
        bg.add(btn_musteriTable_dosyaya_yaz);
        
        musteriTablosunuGuncelle();
        urunTablosuGuncelle();
        faturaTablosunuGuncelle();
    }
    private void faturaTablosunuGuncelle(){
        try{
            List<Fatura> faturaListesi = FaturaDao.faturaListele(user.getId());
            faturaTableModel.setRowCount(0);
            
            for(Fatura fatura: faturaListesi){
                Object[] row = {fatura.getFatura_id(), fatura.getMusteri_id(), fatura.getToplam_tutar()};
                faturaTableModel.addRow(row);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Fatura tablosu getirilemedi.", "uyarı!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void musteriTablosunuGuncelle(){
        try{
            List<Musteri> musteriListesi = MusteriDao.musteriListele(user.getId());
            musteriTableModel.setRowCount(0); //Mevcut satır sayısı 0 yapılır.
            
            for(Musteri musteri: musteriListesi){
                Object[] row = {musteri.getMusteri_id(), musteri.getName(), musteri.getMail()};
                musteriTableModel.addRow(row);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Müşteri tablosu getirilemedi.", "uyarı!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void urunTablosuGuncelle(){
        try{
            List<Urun> urunListesi = UrunDao.urunListele(user.getId());
            urunTableModel.setRowCount(0);
            
            for(Urun urun: urunListesi){
                Object[] row = {urun.getUrun_id(), urun.getUrun_name(), urun.getFiyat()};
                urunTableModel.addRow(row);
            }   
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Ürün tablosu getirilemedi", "uyarı", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        sil_musteri_item = new javax.swing.JMenuItem();
        copy_musteri_item = new javax.swing.JMenuItem();
        popUpUrun = new javax.swing.JPopupMenu();
        sil_urun_item = new javax.swing.JMenuItem();
        copy_urun_item = new javax.swing.JMenuItem();
        popUpFatura = new javax.swing.JPopupMenu();
        sil_fatura_item = new javax.swing.JMenuItem();
        copy_fatura_item = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_musteri = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_urun = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_fatura = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_urunTable_dosyaya_yaz = new javax.swing.JRadioButton();
        btn_txt_area_dosyaya_yaz = new javax.swing.JRadioButton();
        btn_musteriTable_dosyaya_yaz = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btn_faturaFrame = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menu_item_go_add_form = new javax.swing.JMenuItem();

        sil_musteri_item.setText("jMenuItem4");
        sil_musteri_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_musteri_itemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(sil_musteri_item);

        copy_musteri_item.setText("jMenuItem4");
        copy_musteri_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy_musteri_itemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(copy_musteri_item);

        sil_urun_item.setText("jMenuItem1");
        sil_urun_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_urun_itemActionPerformed(evt);
            }
        });
        popUpUrun.add(sil_urun_item);

        copy_urun_item.setText("jMenuItem3");
        copy_urun_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy_urun_itemActionPerformed(evt);
            }
        });
        popUpUrun.add(copy_urun_item);

        sil_fatura_item.setText("jMenuItem1");
        sil_fatura_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_fatura_itemActionPerformed(evt);
            }
        });
        popUpFatura.add(sil_fatura_item);

        copy_fatura_item.setText("jMenuItem3");
        copy_fatura_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy_fatura_itemActionPerformed(evt);
            }
        });
        popUpFatura.add(copy_fatura_item);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setText("burada isim görünür !");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 204));
        jTabbedPane1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setOpaque(false);

        tbl_musteri.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        tbl_musteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Müşteri ID", "Müşteri Ad", "E-Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_musteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_musteriMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_musteri);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Müşteri Tablosu", jPanel2);

        jPanel3.setOpaque(false);

        tbl_urun.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        tbl_urun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ürün ID", "Ürün Ad", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_urun);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ürün Tablosu", jPanel3);

        jPanel4.setOpaque(false);

        tbl_fatura.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        tbl_fatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fatura ID", "Müşteri ID ", "User ID", "Toplam Tutar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_fatura);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fatura Tablosu", jPanel4);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        btn_urunTable_dosyaya_yaz.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_urunTable_dosyaya_yaz.setText("Ürünler tablosunu dosyaya yaz.");
        btn_urunTable_dosyaya_yaz.setOpaque(false);
        btn_urunTable_dosyaya_yaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunTable_dosyaya_yazActionPerformed(evt);
            }
        });

        btn_txt_area_dosyaya_yaz.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_txt_area_dosyaya_yaz.setText("Text Area'yı Dosyaya Yaz");
        btn_txt_area_dosyaya_yaz.setOpaque(false);
        btn_txt_area_dosyaya_yaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_txt_area_dosyaya_yazActionPerformed(evt);
            }
        });

        btn_musteriTable_dosyaya_yaz.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_musteriTable_dosyaya_yaz.setText("Müşteriler tablosunu dosyaya yaz.");
        btn_musteriTable_dosyaya_yaz.setOpaque(false);
        btn_musteriTable_dosyaya_yaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musteriTable_dosyaya_yazActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton1.setText("Profile Git");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_faturaFrame.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btn_faturaFrame.setText("Fatura Oluştur");
        btn_faturaFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faturaFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTabbedPane1)
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_txt_area_dosyaya_yaz, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_urunTable_dosyaya_yaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_musteriTable_dosyaya_yaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_faturaFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_txt_area_dosyaya_yaz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_musteriTable_dosyaya_yaz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_urunTable_dosyaya_yaz)
                        .addGap(92, 92, 92)
                        .addComponent(btn_faturaFrame)
                        .addGap(179, 179, 179)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N

        menu_item_go_add_form.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        menu_item_go_add_form.setText(" Müşteri / Ürün EKle");
        menu_item_go_add_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_go_add_formActionPerformed(evt);
            }
        });
        jMenu2.add(menu_item_go_add_form);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_go_add_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_go_add_formActionPerformed
        EklemeFormu ef = new EklemeFormu(user);
        ef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_item_go_add_formActionPerformed

    private void sil_musteri_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_musteri_itemActionPerformed
        int selectedRow = tbl_musteri.getSelectedRow();
        if(selectedRow != -1){
            int musteriId = (int) musteriTableModel.getValueAt(selectedRow, 0);
            try{
                MusteriDao.musteriSil(musteriId, user.getId());
                musteriTablosunuGuncelle();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "müşteri silinemedi!", "hata", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Lütfen silmek istediğiniz müşteriyi seçiniz. ", "uyarı", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sil_musteri_itemActionPerformed
//Sağ tıklama olayını dinler.
    private void tbl_musteriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_musteriMouseReleased
        /*if(evt.isPopupTrigger()){
            JOptionPane.showMessageDialog(this, "başarılııı");
            int row = tbl_musteri.rowAtPoint(evt.getPoint());
            if(row >= 0 && row < tbl_musteri.getRowCount()){
                tbl_musteri.setRowSelectionInterval(row, row);
            } else{
                tbl_musteri.clearSelection();
            }
            jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
            JOptionPane.showMessageDialog(this, "başarısızz");
        */
    }//GEN-LAST:event_tbl_musteriMouseReleased

    private void copy_musteri_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copy_musteri_itemActionPerformed
            int selectedRow = tbl_musteri.getSelectedRow();
            if (selectedRow != -1) {
                StringBuilder stringBuilder = new StringBuilder();
                int columnCount = musteriTableModel.getColumnCount();
                for (int i = 0; i < columnCount; i++) {
                    stringBuilder.append(musteriTableModel.getValueAt(selectedRow, i).toString()).append(",");
                }
                StringSelection stringSelection = new StringSelection(stringBuilder.toString());
                Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);
                JOptionPane.showMessageDialog(MainFrame.this, "Satır bilgileri kopyalandı!");
            } else {
                JOptionPane.showMessageDialog(this, "Lütfen kopyalamak istediğiniz satırı seçin.", "Uyarı", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_copy_musteri_itemActionPerformed

    private void btn_txt_area_dosyaya_yazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_txt_area_dosyaya_yazActionPerformed
        Helper.dosyayaYaz(jTextArea1, "textAreaVerilerim.csv");
    }//GEN-LAST:event_btn_txt_area_dosyaya_yazActionPerformed

    private void btn_urunTable_dosyaya_yazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunTable_dosyaya_yazActionPerformed
        Helper.dosyayaYaz(urunTableModel, "urunVeriler.csv");
    }//GEN-LAST:event_btn_urunTable_dosyaya_yazActionPerformed

    private void btn_musteriTable_dosyaya_yazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musteriTable_dosyaya_yazActionPerformed
        Helper.dosyayaYaz(musteriTableModel, "musteriVeriler.csv");
    }//GEN-LAST:event_btn_musteriTable_dosyaya_yazActionPerformed

    private void sil_urun_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_urun_itemActionPerformed
        int selectedRow = tbl_urun.getSelectedRow();
        if(selectedRow != -1){
            int urun_id = (int) urunTableModel.getValueAt(selectedRow, 0);
            try{
                UrunDao.urunSil(urun_id, user.getId());
                urunTablosuGuncelle();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Ürün silinemedi!", "hata", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Lütfen silmek istediğiniz müşteriyi seçiniz. ", "uyarı", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sil_urun_itemActionPerformed

    private void copy_urun_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copy_urun_itemActionPerformed
        int selectedRow = tbl_urun.getSelectedRow();
        if (selectedRow != -1) {
            StringBuilder stringBuilder = new StringBuilder();
            int columnCount = urunTableModel.getColumnCount();
            for (int i = 0; i < columnCount; i++) {
                stringBuilder.append(urunTableModel.getValueAt(selectedRow, i).toString()).append(",");
            }
            StringSelection stringSelection = new StringSelection(stringBuilder.toString());
            Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);
            JOptionPane.showMessageDialog(MainFrame.this, "Satır bilgileri kopyalandı!");
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen kopyalamak istediğiniz satırı seçin.", "Uyarı", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_copy_urun_itemActionPerformed

    private void sil_fatura_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_fatura_itemActionPerformed
        int selectedRow = tbl_fatura.getSelectedRow();
        if(selectedRow != -1){
            int fatura_id = (int) faturaTableModel.getValueAt(selectedRow, 0);
            try{
                FaturaDao.faturaSil(fatura_id, user.getId());
                urunTablosuGuncelle();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Fatura silinemedi!", "hata", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Lütfen silmek istediğiniz müşteriyi seçiniz. ", "uyarı", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sil_fatura_itemActionPerformed

    private void copy_fatura_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copy_fatura_itemActionPerformed
        int selectedRow = tbl_fatura.getSelectedRow();
        if (selectedRow != -1) {
            StringBuilder stringBuilder = new StringBuilder();
            int columnCount = faturaTableModel.getColumnCount();
            for (int i = 0; i < columnCount; i++) {
                stringBuilder.append(faturaTableModel.getValueAt(selectedRow, i).toString()).append(",");
            }
            StringSelection stringSelection = new StringSelection(stringBuilder.toString());
            Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);
            JOptionPane.showMessageDialog(MainFrame.this, "Satır bilgileri kopyalandı!");
        } else {
            JOptionPane.showMessageDialog(this, "Lütfen kopyalamak istediğiniz satırı seçin.", "Uyarı", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_copy_fatura_itemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProfileFrame pf = new ProfileFrame(user);
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_faturaFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faturaFrameActionPerformed
        FaturaFrame ff = new FaturaFrame(user);
        ff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_faturaFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(new User()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_faturaFrame;
    private javax.swing.JRadioButton btn_musteriTable_dosyaya_yaz;
    private javax.swing.JRadioButton btn_txt_area_dosyaya_yaz;
    private javax.swing.JRadioButton btn_urunTable_dosyaya_yaz;
    private javax.swing.JMenuItem copy_fatura_item;
    private javax.swing.JMenuItem copy_musteri_item;
    private javax.swing.JMenuItem copy_urun_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem menu_item_go_add_form;
    private javax.swing.JPopupMenu popUpFatura;
    private javax.swing.JPopupMenu popUpUrun;
    private javax.swing.JMenuItem sil_fatura_item;
    private javax.swing.JMenuItem sil_musteri_item;
    private javax.swing.JMenuItem sil_urun_item;
    private javax.swing.JTable tbl_fatura;
    private javax.swing.JTable tbl_musteri;
    private javax.swing.JTable tbl_urun;
    // End of variables declaration//GEN-END:variables
}
